@apiUrl = https://localhost:44308/api/customers
@customerId = CF223568-14AA-4ED4-A38C-801F8D1F5517


### Get customer by id
GET {{apiUrl}}/{{customerId}}


### Get customer addresses
GET {{apiUrl}}/GetAddreses/{{customerId}}


### Add customer address
POST {{apiUrl}}/CreateAddress
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000000",
  "addressLine1": "212 Boshoff street",
  "addressLine2": "Nieuwe Muckleneuk",
  "addressLine3": "Pretoria",
  "addressType": 1,
  "postalCode": "0181",
  "userId": "{{customerId}}"
}

### Add Customer medical scheme
POST  {{apiUrl}}/addmedicalscheme
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "medicalSchemeId": "72023820-E822-444E-8A9D-CBFBEBB9C125",
  "membershipNo": "12543678"
}